name: UnitTest 

on:
  push:
    paths:
      - '**/ut/**.go'
  pull_request:
    paths:
      - '**/ut/**.go'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Declare
        run: echo Test Start!

      - name: Test
        run: cd ./ut; go test -v