name: UnitTest 

on:
  push:
    branches: [ main ] 

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Move
        run: cd ut

      - name: List Up
        run: ls -al

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...